apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-api-gateway
  namespace: default
  annotations:
    # Tell K8s that Kong is managing these routes
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
    - host: clientmanger.tech # Replace with your actual IP or domain
      http:
        paths:
          # ROUTE 1: PUBLIC LOGIN
          - path: /v1/auth/login
            pathType: Prefix
            backend:
              service:
                name: fastapi-service
                port:
                  number: 8000

          # ROUTE 2: PROTECTED AI AGENTS
          - path: /v1/agents
            pathType: Prefix
            backend:
              service:
                name: fastapi-service
                port:
                  number: 8000

---
# Attach the JWT plugin ONLY to the protected route using Kong's special routing CRD
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: protected-api-gateway
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "kong"
    # This single line attaches the security bouncer!
    konghq.com/plugins: "jwt-auth"
spec:
  rules:
    - host: clientmanger.tech
      http:
        paths:
          - path: /v1/agents
            pathType: Prefix
            backend:
              service:
                name: fastapi-service
                port:
                  number: 8000