apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: clientmanager-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "50"

spec:
  ingressClassName: nginx

  rules:
    - host: clientmanger.tech

      http:
        paths:
          - path: /

            pathType: Prefix

            backend:
              service:
                name: clientmanager-api

                port:
                  number: 80